#http://prettier.io/docs/en/option.html

#specify correct parser
parser: babel
filepath: ''

#main settings
printWidth: 120
tabWidth: 2
useTabs: false
semi: true
singleQuote: true
quoteProps: as-needed
trailingComma: all
bracketSpacing: true
jsxBracketSameLine: false
jsxSingleQuote: false
arrowParens: avoid
endOfLine: If

#process always
requirePragma: false
insertPragma: false

#for Markdown
#proseWrap: preserve
#for HTML
#htmlWhitespaceSensitivity: css

overrides:
- files: '*.json'
option:
parser: json
- files:
- '*.md'
- '*.markdown'
option:
parser: markdown
- files:
- '*.ts'
- '*.tsx'
option:
parser: typescript
- files:
- '*.yml'
- '*.yaml'
option:
parser: yaml