#/.circleci/config.yml
#refer: http://circleci.com/docs/2.1/language-javascript/
version: 2.1

executors:
node-Its:
docker:
- image: circleci/node:12.13
working_directory: ~/repo

commands:
setup:
steps:
- checkout
-restore_cache:
keys:
-vl-dependencies-{{checksum "package.json"}}
-vl-dependencies-

jobs:
build:
executor: node-Its
steps:
- setup
- run: yarn
- save_cache:
paths:
- node_modules
key: vl-dependencies-{{checksum "package.json"}}

test:
executor: node-Its
steps:
- setup
- run:
command: |
yarn type-check
yarn lint
yarn coverage
- store_artifacts:
path: ~/repo/coverage

workflows:
version: 2
test:
jobs:
- build
- test:
requires:
- build

